jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Consolas font
        run: |
          sudo apt-get update
          sudo apt-get install -y ttf-mscorefonts-installer
          fc-cache -f -v

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests seaborn matplotlib pillow colorthief
