name: Run Python Script Every 15 Minutes

on:
  schedule:
    # Runs every 15 minutes
    - cron: "*/15 * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with the Python version you are using

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      # Run the Python script
      - name: Run Python script
        run: python your_script.py
