name: Run Python Script Every 15 Minutes

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run Python script
        run: python price_api.py

      - name: Commit and push changes
        run: |
          git config --global simon.faltz 'github-actions'
          git config --global simon.faltz@web.de 'github-actions@github.com'
          git add price_tracking/*.csv
          git commit -m "Update price data"
          git push
